# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('titol_categoria', models.CharField(max_length=50, verbose_name='Titol de la categoria')),
            ],
            options={
                'ordering': ['titol_categoria'],
            },
        ),
        migrations.CreateModel(
            name='post_noticia',
            fields=[
                ('id_post_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titol_post_noticia', models.CharField(max_length=100, verbose_name='Titol noticia')),
                ('text_post_noticia', models.TextField(verbose_name='Contingut de la noticia')),
                ('creacio_post_noticia', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor_post_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titol_post_noticia'],
            },
        ),
    ]
