# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nom_empresa']},
        ),
    ]
