# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20160920_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='centre',
            fields=[
                ('id_centre', models.AutoField(primary_key=True, serialize=False)),
                ('nom_centre', models.CharField(max_length=50)),
                ('cit_centre', models.CharField(max_length=20)),
                ('cp_centre', models.CharField(max_length=5)),
                ('mail_centre', models.EmailField(max_length=80)),
                ('encarregat_centre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom_centre'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='mail_empresa',
            field=models.EmailField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nom_empresa',
            field=models.CharField(max_length=40, verbose_name='Nom Empresa'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cod_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
